/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroAsistenteRouteImport } from './routes/registro-asistente'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RegistradorRouteImport } from './routes/registrador'
import { Route as MisEntradasRouteImport } from './routes/mis-entradas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExpositorRouteImport } from './routes/expositor'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackofficeIndexRouteImport } from './routes/backoffice.index'
import { Route as BackofficeStandsRouteImport } from './routes/backoffice.stands'
import { Route as BackofficeReservasRouteImport } from './routes/backoffice.reservas'
import { Route as BackofficeRegistradoresRouteImport } from './routes/backoffice.registradores'
import { Route as BackofficePerfilRouteImport } from './routes/backoffice.perfil'
import { Route as BackofficePatrocinadoresRouteImport } from './routes/backoffice.patrocinadores'
import { Route as BackofficeOrdenesRouteImport } from './routes/backoffice.ordenes'
import { Route as BackofficeExpositoresRouteImport } from './routes/backoffice.expositores'
import { Route as BackofficeEventoRouteImport } from './routes/backoffice.evento'
import { Route as BackofficeEntradasRouteImport } from './routes/backoffice.entradas'
import { Route as BackofficeDisertantesRouteImport } from './routes/backoffice.disertantes'
import { Route as BackofficeBannersRouteImport } from './routes/backoffice.banners'
import { Route as BackofficeB2bRouteImport } from './routes/backoffice.b2b'

const RegistroAsistenteRoute = RegistroAsistenteRouteImport.update({
  id: '/registro-asistente',
  path: '/registro-asistente',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistradorRoute = RegistradorRouteImport.update({
  id: '/registrador',
  path: '/registrador',
  getParentRoute: () => rootRouteImport,
} as any)
const MisEntradasRoute = MisEntradasRouteImport.update({
  id: '/mis-entradas',
  path: '/mis-entradas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpositorRoute = ExpositorRouteImport.update({
  id: '/expositor',
  path: '/expositor',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeIndexRoute = BackofficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeStandsRoute = BackofficeStandsRouteImport.update({
  id: '/stands',
  path: '/stands',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeReservasRoute = BackofficeReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeRegistradoresRoute = BackofficeRegistradoresRouteImport.update({
  id: '/registradores',
  path: '/registradores',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficePerfilRoute = BackofficePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficePatrocinadoresRoute =
  BackofficePatrocinadoresRouteImport.update({
    id: '/patrocinadores',
    path: '/patrocinadores',
    getParentRoute: () => BackofficeRoute,
  } as any)
const BackofficeOrdenesRoute = BackofficeOrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeExpositoresRoute = BackofficeExpositoresRouteImport.update({
  id: '/expositores',
  path: '/expositores',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeEventoRoute = BackofficeEventoRouteImport.update({
  id: '/evento',
  path: '/evento',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeEntradasRoute = BackofficeEntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeDisertantesRoute = BackofficeDisertantesRouteImport.update({
  id: '/disertantes',
  path: '/disertantes',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeBannersRoute = BackofficeBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeB2bRoute = BackofficeB2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => BackofficeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/expositor': typeof ExpositorRoute
  '/login': typeof LoginRoute
  '/mis-entradas': typeof MisEntradasRoute
  '/registrador': typeof RegistradorRoute
  '/registro': typeof RegistroRoute
  '/registro-asistente': typeof RegistroAsistenteRoute
  '/backoffice/b2b': typeof BackofficeB2bRoute
  '/backoffice/banners': typeof BackofficeBannersRoute
  '/backoffice/disertantes': typeof BackofficeDisertantesRoute
  '/backoffice/entradas': typeof BackofficeEntradasRoute
  '/backoffice/evento': typeof BackofficeEventoRoute
  '/backoffice/expositores': typeof BackofficeExpositoresRoute
  '/backoffice/ordenes': typeof BackofficeOrdenesRoute
  '/backoffice/patrocinadores': typeof BackofficePatrocinadoresRoute
  '/backoffice/perfil': typeof BackofficePerfilRoute
  '/backoffice/registradores': typeof BackofficeRegistradoresRoute
  '/backoffice/reservas': typeof BackofficeReservasRoute
  '/backoffice/stands': typeof BackofficeStandsRoute
  '/backoffice/': typeof BackofficeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expositor': typeof ExpositorRoute
  '/login': typeof LoginRoute
  '/mis-entradas': typeof MisEntradasRoute
  '/registrador': typeof RegistradorRoute
  '/registro': typeof RegistroRoute
  '/registro-asistente': typeof RegistroAsistenteRoute
  '/backoffice/b2b': typeof BackofficeB2bRoute
  '/backoffice/banners': typeof BackofficeBannersRoute
  '/backoffice/disertantes': typeof BackofficeDisertantesRoute
  '/backoffice/entradas': typeof BackofficeEntradasRoute
  '/backoffice/evento': typeof BackofficeEventoRoute
  '/backoffice/expositores': typeof BackofficeExpositoresRoute
  '/backoffice/ordenes': typeof BackofficeOrdenesRoute
  '/backoffice/patrocinadores': typeof BackofficePatrocinadoresRoute
  '/backoffice/perfil': typeof BackofficePerfilRoute
  '/backoffice/registradores': typeof BackofficeRegistradoresRoute
  '/backoffice/reservas': typeof BackofficeReservasRoute
  '/backoffice/stands': typeof BackofficeStandsRoute
  '/backoffice': typeof BackofficeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/expositor': typeof ExpositorRoute
  '/login': typeof LoginRoute
  '/mis-entradas': typeof MisEntradasRoute
  '/registrador': typeof RegistradorRoute
  '/registro': typeof RegistroRoute
  '/registro-asistente': typeof RegistroAsistenteRoute
  '/backoffice/b2b': typeof BackofficeB2bRoute
  '/backoffice/banners': typeof BackofficeBannersRoute
  '/backoffice/disertantes': typeof BackofficeDisertantesRoute
  '/backoffice/entradas': typeof BackofficeEntradasRoute
  '/backoffice/evento': typeof BackofficeEventoRoute
  '/backoffice/expositores': typeof BackofficeExpositoresRoute
  '/backoffice/ordenes': typeof BackofficeOrdenesRoute
  '/backoffice/patrocinadores': typeof BackofficePatrocinadoresRoute
  '/backoffice/perfil': typeof BackofficePerfilRoute
  '/backoffice/registradores': typeof BackofficeRegistradoresRoute
  '/backoffice/reservas': typeof BackofficeReservasRoute
  '/backoffice/stands': typeof BackofficeStandsRoute
  '/backoffice/': typeof BackofficeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backoffice'
    | '/expositor'
    | '/login'
    | '/mis-entradas'
    | '/registrador'
    | '/registro'
    | '/registro-asistente'
    | '/backoffice/b2b'
    | '/backoffice/banners'
    | '/backoffice/disertantes'
    | '/backoffice/entradas'
    | '/backoffice/evento'
    | '/backoffice/expositores'
    | '/backoffice/ordenes'
    | '/backoffice/patrocinadores'
    | '/backoffice/perfil'
    | '/backoffice/registradores'
    | '/backoffice/reservas'
    | '/backoffice/stands'
    | '/backoffice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/expositor'
    | '/login'
    | '/mis-entradas'
    | '/registrador'
    | '/registro'
    | '/registro-asistente'
    | '/backoffice/b2b'
    | '/backoffice/banners'
    | '/backoffice/disertantes'
    | '/backoffice/entradas'
    | '/backoffice/evento'
    | '/backoffice/expositores'
    | '/backoffice/ordenes'
    | '/backoffice/patrocinadores'
    | '/backoffice/perfil'
    | '/backoffice/registradores'
    | '/backoffice/reservas'
    | '/backoffice/stands'
    | '/backoffice'
  id:
    | '__root__'
    | '/'
    | '/backoffice'
    | '/expositor'
    | '/login'
    | '/mis-entradas'
    | '/registrador'
    | '/registro'
    | '/registro-asistente'
    | '/backoffice/b2b'
    | '/backoffice/banners'
    | '/backoffice/disertantes'
    | '/backoffice/entradas'
    | '/backoffice/evento'
    | '/backoffice/expositores'
    | '/backoffice/ordenes'
    | '/backoffice/patrocinadores'
    | '/backoffice/perfil'
    | '/backoffice/registradores'
    | '/backoffice/reservas'
    | '/backoffice/stands'
    | '/backoffice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackofficeRoute: typeof BackofficeRouteWithChildren
  ExpositorRoute: typeof ExpositorRoute
  LoginRoute: typeof LoginRoute
  MisEntradasRoute: typeof MisEntradasRoute
  RegistradorRoute: typeof RegistradorRoute
  RegistroRoute: typeof RegistroRoute
  RegistroAsistenteRoute: typeof RegistroAsistenteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro-asistente': {
      id: '/registro-asistente'
      path: '/registro-asistente'
      fullPath: '/registro-asistente'
      preLoaderRoute: typeof RegistroAsistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrador': {
      id: '/registrador'
      path: '/registrador'
      fullPath: '/registrador'
      preLoaderRoute: typeof RegistradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-entradas': {
      id: '/mis-entradas'
      path: '/mis-entradas'
      fullPath: '/mis-entradas'
      preLoaderRoute: typeof MisEntradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expositor': {
      id: '/expositor'
      path: '/expositor'
      fullPath: '/expositor'
      preLoaderRoute: typeof ExpositorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/stands': {
      id: '/backoffice/stands'
      path: '/stands'
      fullPath: '/backoffice/stands'
      preLoaderRoute: typeof BackofficeStandsRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/reservas': {
      id: '/backoffice/reservas'
      path: '/reservas'
      fullPath: '/backoffice/reservas'
      preLoaderRoute: typeof BackofficeReservasRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/registradores': {
      id: '/backoffice/registradores'
      path: '/registradores'
      fullPath: '/backoffice/registradores'
      preLoaderRoute: typeof BackofficeRegistradoresRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/perfil': {
      id: '/backoffice/perfil'
      path: '/perfil'
      fullPath: '/backoffice/perfil'
      preLoaderRoute: typeof BackofficePerfilRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/patrocinadores': {
      id: '/backoffice/patrocinadores'
      path: '/patrocinadores'
      fullPath: '/backoffice/patrocinadores'
      preLoaderRoute: typeof BackofficePatrocinadoresRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/ordenes': {
      id: '/backoffice/ordenes'
      path: '/ordenes'
      fullPath: '/backoffice/ordenes'
      preLoaderRoute: typeof BackofficeOrdenesRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/expositores': {
      id: '/backoffice/expositores'
      path: '/expositores'
      fullPath: '/backoffice/expositores'
      preLoaderRoute: typeof BackofficeExpositoresRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/evento': {
      id: '/backoffice/evento'
      path: '/evento'
      fullPath: '/backoffice/evento'
      preLoaderRoute: typeof BackofficeEventoRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/entradas': {
      id: '/backoffice/entradas'
      path: '/entradas'
      fullPath: '/backoffice/entradas'
      preLoaderRoute: typeof BackofficeEntradasRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/disertantes': {
      id: '/backoffice/disertantes'
      path: '/disertantes'
      fullPath: '/backoffice/disertantes'
      preLoaderRoute: typeof BackofficeDisertantesRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/banners': {
      id: '/backoffice/banners'
      path: '/banners'
      fullPath: '/backoffice/banners'
      preLoaderRoute: typeof BackofficeBannersRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/b2b': {
      id: '/backoffice/b2b'
      path: '/b2b'
      fullPath: '/backoffice/b2b'
      preLoaderRoute: typeof BackofficeB2bRouteImport
      parentRoute: typeof BackofficeRoute
    }
  }
}

interface BackofficeRouteChildren {
  BackofficeB2bRoute: typeof BackofficeB2bRoute
  BackofficeBannersRoute: typeof BackofficeBannersRoute
  BackofficeDisertantesRoute: typeof BackofficeDisertantesRoute
  BackofficeEntradasRoute: typeof BackofficeEntradasRoute
  BackofficeEventoRoute: typeof BackofficeEventoRoute
  BackofficeExpositoresRoute: typeof BackofficeExpositoresRoute
  BackofficeOrdenesRoute: typeof BackofficeOrdenesRoute
  BackofficePatrocinadoresRoute: typeof BackofficePatrocinadoresRoute
  BackofficePerfilRoute: typeof BackofficePerfilRoute
  BackofficeRegistradoresRoute: typeof BackofficeRegistradoresRoute
  BackofficeReservasRoute: typeof BackofficeReservasRoute
  BackofficeStandsRoute: typeof BackofficeStandsRoute
  BackofficeIndexRoute: typeof BackofficeIndexRoute
}

const BackofficeRouteChildren: BackofficeRouteChildren = {
  BackofficeB2bRoute: BackofficeB2bRoute,
  BackofficeBannersRoute: BackofficeBannersRoute,
  BackofficeDisertantesRoute: BackofficeDisertantesRoute,
  BackofficeEntradasRoute: BackofficeEntradasRoute,
  BackofficeEventoRoute: BackofficeEventoRoute,
  BackofficeExpositoresRoute: BackofficeExpositoresRoute,
  BackofficeOrdenesRoute: BackofficeOrdenesRoute,
  BackofficePatrocinadoresRoute: BackofficePatrocinadoresRoute,
  BackofficePerfilRoute: BackofficePerfilRoute,
  BackofficeRegistradoresRoute: BackofficeRegistradoresRoute,
  BackofficeReservasRoute: BackofficeReservasRoute,
  BackofficeStandsRoute: BackofficeStandsRoute,
  BackofficeIndexRoute: BackofficeIndexRoute,
}

const BackofficeRouteWithChildren = BackofficeRoute._addFileChildren(
  BackofficeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackofficeRoute: BackofficeRouteWithChildren,
  ExpositorRoute: ExpositorRoute,
  LoginRoute: LoginRoute,
  MisEntradasRoute: MisEntradasRoute,
  RegistradorRoute: RegistradorRoute,
  RegistroRoute: RegistroRoute,
  RegistroAsistenteRoute: RegistroAsistenteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
