/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroAsistenteRouteImport } from './routes/registro-asistente'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExpositorRouteImport } from './routes/expositor'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackofficeIndexRouteImport } from './routes/backoffice.index'
import { Route as BackofficeExpositoresRouteImport } from './routes/backoffice.expositores'

const RegistroAsistenteRoute = RegistroAsistenteRouteImport.update({
  id: '/registro-asistente',
  path: '/registro-asistente',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpositorRoute = ExpositorRouteImport.update({
  id: '/expositor',
  path: '/expositor',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeIndexRoute = BackofficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeExpositoresRoute = BackofficeExpositoresRouteImport.update({
  id: '/expositores',
  path: '/expositores',
  getParentRoute: () => BackofficeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/expositor': typeof ExpositorRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/registro-asistente': typeof RegistroAsistenteRoute
  '/backoffice/expositores': typeof BackofficeExpositoresRoute
  '/backoffice/': typeof BackofficeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expositor': typeof ExpositorRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/registro-asistente': typeof RegistroAsistenteRoute
  '/backoffice/expositores': typeof BackofficeExpositoresRoute
  '/backoffice': typeof BackofficeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/expositor': typeof ExpositorRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/registro-asistente': typeof RegistroAsistenteRoute
  '/backoffice/expositores': typeof BackofficeExpositoresRoute
  '/backoffice/': typeof BackofficeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backoffice'
    | '/expositor'
    | '/login'
    | '/registro'
    | '/registro-asistente'
    | '/backoffice/expositores'
    | '/backoffice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/expositor'
    | '/login'
    | '/registro'
    | '/registro-asistente'
    | '/backoffice/expositores'
    | '/backoffice'
  id:
    | '__root__'
    | '/'
    | '/backoffice'
    | '/expositor'
    | '/login'
    | '/registro'
    | '/registro-asistente'
    | '/backoffice/expositores'
    | '/backoffice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackofficeRoute: typeof BackofficeRouteWithChildren
  ExpositorRoute: typeof ExpositorRoute
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
  RegistroAsistenteRoute: typeof RegistroAsistenteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro-asistente': {
      id: '/registro-asistente'
      path: '/registro-asistente'
      fullPath: '/registro-asistente'
      preLoaderRoute: typeof RegistroAsistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expositor': {
      id: '/expositor'
      path: '/expositor'
      fullPath: '/expositor'
      preLoaderRoute: typeof ExpositorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/expositores': {
      id: '/backoffice/expositores'
      path: '/expositores'
      fullPath: '/backoffice/expositores'
      preLoaderRoute: typeof BackofficeExpositoresRouteImport
      parentRoute: typeof BackofficeRoute
    }
  }
}

interface BackofficeRouteChildren {
  BackofficeExpositoresRoute: typeof BackofficeExpositoresRoute
  BackofficeIndexRoute: typeof BackofficeIndexRoute
}

const BackofficeRouteChildren: BackofficeRouteChildren = {
  BackofficeExpositoresRoute: BackofficeExpositoresRoute,
  BackofficeIndexRoute: BackofficeIndexRoute,
}

const BackofficeRouteWithChildren = BackofficeRoute._addFileChildren(
  BackofficeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackofficeRoute: BackofficeRouteWithChildren,
  ExpositorRoute: ExpositorRoute,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
  RegistroAsistenteRoute: RegistroAsistenteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
